#!/bin/bash

TITLE="$1"

FILENAME=$(echo "${TITLE// /_}.svx" | tr '[:upper:]' '[:lower:]')

echo "$TITLE" | node ./distractions-entry.js >> ./src/data/distractions.yaml
touch "./src/routes/distractions/$FILENAME"

git add .
git commit -m "Added new distractions blog post: $1"

