#!/bin/bash

DOODLE_TITLE="$1"
ALT_TEXT="$2"

DOODLE_FILENAME="${DOODLE_TITLE// /_}.jpg"
NEW_DOODLE="$(ls ./new-doodles | grep '\.jpg$')"
mv "./new-doodles/$NEW_DOODLE" "./static/original-doodles/$DOODLE_FILENAME"

./add-doodle-from-file $DOODLE_FILENAME "$ALT_TEXT"

git add .
git commit -m "Attempted auto add of $1 with alt text $2"
git push

